#!/usr/bin/python
import time
from hosted import device

while True: 
  device.gpio.setup_pin(26, direction="out")
  device.gpio.set_pin_value(1234, high=False)
  time.sleep(1)
  device.gpio.set_pin_value(1234, high=True)
  time.sleep(1)
