#!/usr/bin/python2.7
from hosted import device
import time, random
device.gpio.setup_pin(4, direction="out")
device.gpio.set_pin_value(4,  high=True)
time.sleep(5)
device.gpio.set_pin_value(4,  high=False)
time.sleep(random.randint(60, 600))
